README.md, helm/alfresco-process-infrastructure/requirements.yaml, helm/alfresco-process-infrastructure/values.yaml
AAE-940 - added NFS for connector volume
=> added NFS for connector volume

helm/alfresco-process-infrastructure/alfresco-aps-realm.json
For QA needed we need to provide another user with ACTIVITI_MODELER role OOTB.
=> Add another default modeler user

helm/alfresco-process-infrastructure/values.yaml
=> [AAE-1111] - add Identity host variable for modelling-app

helm/alfresco-process-infrastructure/values.yaml
=> [DW-1356] - add internalPort for alfresco-admin-app

helm/alfresco-process-infrastructure/values.yaml
=> [AAE-1922] - update presistence to readwriteonce

helm/alfresco-process-infrastructure/values.yaml
=> [AAE-2096] - update modeling-app internal port

helm/alfresco-process-infrastructure/values.yaml
Override the provider value with ALL
Add the bpm variable for workspace
=> [ACA-2945] Provide the bpm endpoint and enable provider ALL

helm/alfresco-process-infrastructure/README.md, helm/alfresco-process-infrastructure/values.yaml
Addressing this issue: https://issues.alfresco.com/jira/browse/AAE-2342
=> AAE-2342 Remove internal port value since it is a default

helm/alfresco-process-infrastructure/values.yaml
=> [AAE-2422] - update image from M6 to develop branch

helm/alfresco-process-infrastructure/README.md, helm/alfresco-process-infrastructure/requirements.yaml, helm/alfresco-process-infrastructure/templates/NOTES.txt, helm/alfresco-process-infrastructure/templates/setup-acs-script-job.yaml, helm/alfresco-process-infrastructure/values.yaml
- update setup-acs script to run as job
- remove dependency of ACS from alfresco-deployment-service
[ACS-26]
=> [ACS-26] - remove ACS deployment from AAE chart

helm/alfresco-process-infrastructure/requirements.yaml, helm/alfresco-process-infrastructure/values.yaml
Updating admin and model ingress path values
=> Updating model and admin app ingress path value

helm/alfresco-process-infrastructure/requirements.yaml
=> [AAE-1964] - Upgrade to Identity Service 1.2 (Keycloak 8.0.1)

helm/alfresco-process-infrastructure/requirements.yaml, helm/alfresco-process-infrastructure/values.yaml
=> [AAE-2605] - upgrade apiVersion and postgres chart to support Kubernetes version 1.16

helm/alfresco-process-infrastructure/values.yaml
=> [AAE-2783] - add extraEnv for application.database.external

helm/alfresco-process-infrastructure/README.md, helm/alfresco-process-infrastructure/requirements.yaml
=> AAE-2951 upgrade identity chart to 2.1.0

.pre-commit-config.yaml, .travis.yml, helm/alfresco-process-infrastructure/README.md
=> AAE-2739 validate k8s version 1.15 to 1.17 compat

helm/alfresco-process-infrastructure/README.md, helm/alfresco-process-infrastructure/values.yaml
Depends on https://github.com/Alfresco/alfresco-modeling-service/pull/155
=> AAE-4362 Enable liquibase as initContainer

helm/alfresco-process-infrastructure/README.md, helm/alfresco-process-infrastructure/requirements.yaml, helm/alfresco-process-infrastructure/values.yaml
=> AAE-5479 bump up identity service to 1.5.0

helm/alfresco-process-infrastructure/functions_acs.sh, helm/alfresco-process-infrastructure/setup_acs.sh
even though they shouldn't be used (as authentication should remain confimed at keycoak level) we don't want to have simple or hardcoded passwords.
ref AAE-5586
=> AAE-5586 make password strong and random

helm/alfresco-process-infrastructure/README.md, helm/alfresco-process-infrastructure/values.yaml
This PR updates Deployment Service probes using liveness and readiness health checks
=> fix(AAE-6248): Update Deployment service liveness and readiness probes
